### ISSUE TITLE
Fix recently failing CI

### ISSUE THREAD

**Issue by zachborboa** [php-curl-class/php-curl-class#769]
Last green ✅:
https://github.com/php-curl-class/php-curl-class/actions/runs/4284849677/jobs/7462372454

Then red ❌:
https://github.com/php-curl-class/php-curl-class/actions/runs/4295440765/jobs/7485860759

```
++ [[ -f vendor/bin/phpcs ]]
++ phpcs_to_use=vendor/bin/phpcs
++ vendor/bin/phpcs --version
PHP_CodeSniffer version 3.7.2 (stable) by Squiz (http://www.squiz.net/)
++ vendor/bin/phpcs --extensions=php '--ignore=*/vendor/*' --standard=tests/ruleset.xml -p -s .
PHP Fatal error:  Uncaught Error: Class "PHPCSUtils\Tokens\Collections" not found in /home/runner/work/php-curl-class/php-curl-class/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniffs/Keywords/CaseSensitiveKeywordsSniff.php:41
Stack trace:
#0 /home/runner/work/php-curl-class/php-curl-class/vendor/squizlabs/php_codesniffer/src/Ruleset.php(1236): PHPCompatibility\Sniffs\Keywords\CaseSensitiveKeywordsSniff->register()
#1 /home/runner/work/php-curl-class/php-curl-class/vendor/squizlabs/php_codesniffer/src/Ruleset.php(218): PHP_CodeSniffer\Ruleset->populateTokenListeners()
#2 /home/runner/work/php-curl-class/php-curl-class/vendor/squizlabs/php_codesniffer/src/Runner.php(336): PHP_CodeSniffer\Ruleset->__construct()
#3 /home/runner/work/php-curl-class/php-curl-class/vendor/squizlabs/php_codesniffer/src/Runner.php(72): PHP_CodeSniffer\Runner->init()
#4 /home/runner/work/php-curl-class/php-curl-class/vendor/squizlabs/php_codesniffer/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#5 /home/runner/work/php-curl-class/php-curl-class/vendor/bin/phpcs(120): include('...')
#6 {main}
  thrown in /home/runner/work/php-curl-class/php-curl-class/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniffs/Keywords/CaseSensitiveKeywordsSniff.php on line 41
++ [[ 255 -ne 0 ]]
Error: found standard violation(s)
++ echo 'Error: found standard violation(s)'

++ errors+=("found standard violation(s)")
Errors found: 2
+ set +x

Error 1 of 2:
	phpunit command failed

Error 2 of 2:
	found standard violation(s)
Error: Process completed with exit code 2.
```

**Comment by zachborboa** [comment]
Resolved self without any changes
