### ISSUE TITLE
Curl->diagnose(), uncaught type error if Content-Type is null, PHP 8.1.13

### ISSUE THREAD

**Issue by CharlesReace** [php-curl-class/php-curl-class#777]
What is the expected behavior?

- To finish outputting diagnostics without an exception if for some reason Content-Type is NULL at that point

What is the actual behavior?

```
Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, null given in /var/www/html/mist/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php:1392
Stack trace:
#0 /var/www/html/****/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php(1392): preg_match('/^(?:applicatio...', NULL)
#1 /var/www/html/****/****/****t.php(49): Curl\Curl->diagnose()
```
What steps will reproduce the problem?

- In my case, occurred when attempting to connect to an endpoint that returned a HTTP 502, apparently with no Content-Type response header?

Possible solution: maybe add a quick check that it's not empty, e.g.:
```php
if (!empty($this->responseHeaders['Content-Type']) && preg_match($this->jsonPattern, $this->responseHeaders['Content-Type'])) {
```
The `diagnose()` output up until the point where it died:

```
ERROR: HTTP/1.1 502 Bad Gateway

--- Begin PHP Curl Class diagnostic output ---
PHP Curl Class version: 9.14.1
PHP version: 8.1.13
Curl version: 7.74.0
Request contained 16 options:
    1 CURLOPT_PROTOCOLS: 3
    2 CURLOPT_REDIR_PROTOCOLS: 3
    3 CURLOPT_USERAGENT: PHP-Curl-Class/9.14.1 (+https://github.com/php-curl-class/php-curl-class) PHP/8.1.13 curl/7.74.0
    4 CURLOPT_TIMEOUT: 5
    5 CURLINFO_HEADER_OUT: true
    6 CURLOPT_PROGRESSFUNCTION: (callable)
    7 CURLOPT_NOPROGRESS: false
    8 CURLOPT_HEADERFUNCTION: (callable)
    9 CURLOPT_RETURNTRANSFER: true
    10 CURLOPT_HTTPHEADER: array:
array(1) {
  [0]=>
  string(956) "Authorization: Bearer **************************"
}
    11 CURLOPT_SSLKEY: /var/www/html/********.key
    12 CURLOPT_SSLCERT: /var/www/html/********.crt
    13 CURLOPT_URL: https://************/connect
    14 CURLOPT_CUSTOMREQUEST: GET
    15 CURLOPT_HTTPGET: true
    16 CURLOPT_NOBODY: false
Sent an HTTP GET request to "https://****************/connect".
Request contained 5 headers:
    1 Request-Line: GET /**********/connect HTTP/1.1
    2 Host: **********.com
    3 User-Agent: PHP-Curl-Class/9.14.1 (+https://github.com/php-curl-class/php-curl-class) PHP/8.1.13 curl/7.74.0
    4 Accept: */*
    5 Authorization: Bearer *************************
Request contained no body.
Response contains 7 headers:
    1 Status-Line: HTTP/1.1 502 Bad Gateway
    2 X-RateLimit-Limit: 5000
    3 X-RateLimit-Remaining: 4982
    4 X-RateLimit-Reset: 2945
    5 Date: Mon, 15 May 2023 14:57:15 GMT
    6 Connection: keep-alive
    7 Content-Length: 160
Response did not set a content type.
Received an HTTP status code of 502.
Received an HTTP 502 error response with message "HTTP/1.1 502 Bad Gateway".
Received a non-empty response body.
Response content length (from content-length header): 160
```

**Comment by zachborboa** [comment]
Thanks!

**Comment by CharlesReace** [comment]
Thanks for the quick turn-around :)

**Comment by CharlesReace** [comment]
Just wanted to let you know, I upgraded to the latest version, and now the `diagnose()` completes without exception. Thanks!
```
    5 Date: Wed, 17 May 2023 14:42:41 GMT
    6 Connection: keep-alive
    7 Content-Length: 160
Response did not set a content type.
Received an HTTP status code of 502.
Received an HTTP 502 error response with message "HTTP/1.1 502 Bad Gateway".
Received a non-empty response body.
Response content length (from content-length header): 160
--- End PHP Curl Class diagnostic output ---
```
