### ISSUE TITLE
Detected an illegal character in input string in /var/www/site/vendor/symfony/polyfill-mbstring/Mbstring.php:536

### ISSUE THREAD

**Issue by 3kbest** [php-curl-class/php-curl-class#811]
After i upgraded to tag 9.18.1 i got following error.

Code:
```
Uncaught ErrorException: iconv_strpos(): Detected an illegal character in input string in
/var/www/site/vendor/symfony/polyfill-mbstring/Mbstring.php:536
Stack trace:#0 [internal function]: {closure}()
#1 /var/www/site/vendor/symfony/polyfill-mbstring/Mbstring.php(536): iconv_strpos()
#2 /var/www/site/vendor/symfony/polyfill-mbstring/bootstrap80.php(60): Symfony\Polyfill\Mbstring\Mbstring::mb_strpos()
#3 /var/www/site/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php(1950): mb_strpos()
#4 /var/www/site/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php(535): Curl\Curl->parseResponse()
#5 /var/www/site/vendor/php-curl-class/php-curl-class/src/Curl/Curl.php(614): Curl\Curl->exec()
#6 /var/www/site/vendor/3kbest/alphaHue/src/AlphaHue.php(100): Curl\Curl->get()
#7 /var/www/site/vendor/3kbest/alphaHue/src/AlphaHue.php(67): AlphaHue\AlphaHue->getConfiguration()
#8 /var/www/site/cronjob/HueLight.php(150): AlphaHue\AlphaHue->__construct()
#9 /var/www/site/cronjob/HueLight.php(120): CronJobs\HueLight->runLight()
#10 /var/www/site/cronjob/HueLight.php(62): CronJobs\HueLight->handleErrors()
#11 /var/www/site/cronjob/HueLight.php(172): CronJobs\HueLight->__construct()
#12 {main}  thrown in /var/www/site/vendor/symfony/polyfill-mbstring/Mbstring.php on line 536
```

And when i downgrade to 9.17.4 it works fine.

**Comment by zachborboa** [comment]
Hi, thank you for the report. Please install the latest commit version and retry.
```shell
composer require php-curl-class/php-curl-class @dev
```

**Comment by zachborboa** [comment]
Closing as I believe this has been resolved in https://github.com/php-curl-class/php-curl-class/pull/813
